// Code generated by "stringer -type=Proto"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[HTTP10-2]
	_ = x[HTTP11-4]
	_ = x[HTTP2-8]
	_ = x[WebSocket-16]
}

const (
	_Proto_name_0 = "Unknown"
	_Proto_name_1 = "HTTP10"
	_Proto_name_2 = "HTTP11"
	_Proto_name_3 = "HTTP2"
	_Proto_name_4 = "WebSocket"
)

func (i Proto) String() string {
	switch {
	case i == 0:
		return _Proto_name_0
	case i == 2:
		return _Proto_name_1
	case i == 4:
		return _Proto_name_2
	case i == 8:
		return _Proto_name_3
	case i == 16:
		return _Proto_name_4
	default:
		return "Proto(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
