// Code generated by "stringer -type=Setting -output=settings_string.go"; DO NOT EDIT.

package settings

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeaderTableSize-1]
	_ = x[EnablePush-2]
	_ = x[MaxConcurrentStreams-3]
	_ = x[InitialWindowSize-4]
	_ = x[MaxFrameSize-5]
	_ = x[MaxHeaderListSize-6]
}

const _Setting_name = "HeaderTableSizeEnablePushMaxConcurrentStreamsInitialWindowSizeMaxFrameSizeMaxHeaderListSize"

var _Setting_index = [...]uint8{0, 15, 25, 45, 62, 74, 91}

func (i Setting) String() string {
	i -= 1
	if i >= Setting(len(_Setting_index)-1) {
		return "Setting(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Setting_name[_Setting_index[i]:_Setting_index[i+1]]
}
