package mime

var Extension = map[string]MIME{
	".avif": AVIF,
	// TODO: charset MUST NOT be constant, but rather be derived from the file itself
	".css":  "text/css; charset=utf-8",
	".gif":  GIF,
	".htm":  "text/html; charset=utf-8",
	".html": "text/html; charset=utf-8",
	".jpeg": JPEG,
	".jpg":  JPEG,
	".js":   "text/javascript; charset=utf-8",
	".json": JSON,
	".mjs":  "text/javascript; charset=utf-8",
	".pdf":  PDF,
	".png":  PNG,
	".svg":  SVG,
	".wasm": WASM,
	".webp": WEBP,
	".xml":  "text/xml; charset=utf-8",
	".gz":   GZIP,
	".sql":  "application/sql",
	".tzif": "application/tzif",
	".yaml": YAML,
	".xfdf": "application/xfdf",
	".zip":  ZIP,
	".zlib": ZLIB,
	".zstd": ZSTD,
	".ico":  ICO,
}
