package mime

var Extension = map[string]MIME{
	".avif": AVIF,
	".css":  CSS,
	".gif":  GIF,
	".htm":  HTML,
	".html": HTML,
	".jpeg": JPEG,
	".jpg":  JPEG,
	".js":   JAVASCRIPT,
	".mjs":  JAVASCRIPT,
	".json": JSON,
	".pdf":  PDF,
	".png":  PNG,
	".svg":  SVG,
	".wasm": WASM,
	".webp": WEBP,
	".xml":  XML,
	".gz":   GZIP,
	".sql":  SQL,
	".tzif": TZIF,
	".yaml": YAML,
	".xfdf": XFDF,
	".zip":  ZIP,
	".zlib": ZLIB,
	".zstd": ZSTD,
	".ico":  ICO,
}
