package mime

var Extension = map[string]string{
	".avif": "image/avif",
	".css":  "text/css; charset=utf-8",
	".gif":  "image/gif",
	".htm":  "text/html; charset=utf-8",
	".html": "text/html; charset=utf-8",
	".jpeg": "image/jpeg",
	".jpg":  "image/jpeg",
	".js":   "text/javascript; charset=utf-8",
	".json": "application/json",
	".mjs":  "text/javascript; charset=utf-8",
	".pdf":  "application/pdf",
	".png":  "image/png",
	".svg":  "image/svg+xml",
	".wasm": "application/wasm",
	".webp": "image/webp",
	".xml":  "text/xml; charset=utf-8",
	".gz":   "application/gzip",
	".sql":  "application/sql",
	".tzif": "application/tzif",
	".yaml": "application/yaml",
	".xfdf": "application/xfdf",
	".zip":  "application/zip",
	".zlib": "application/zlib",
	".zstd": "application/zstd",
}
